### ISSUE TITLE
Midterm Milestone (june 20th)

### ISSUE THREAD

**Issue by engineerOfLies** [DG526/SummerProject2023#17]
In order to meet the expectations for the June 20th milestone the game will need to demonstration these deliverables:

- [x] A Main menu
- [x] A HUD
- [x] Twin Shooter controls for at least keyboard for movement and mouse for shooting
- [x] Two different Projectiles
- [x] 1 playable level with boundaries
- [x] 3 different enemy types (ankle biter, flyer, grunt)
- [ ] A level boss dragon with 3 different attacks, claw/claw, Bite, Breath
