### ISSUE TITLE
Final Milestone (Minimum Viable Product) Due July 13th

### ISSUE THREAD

**Issue by engineerOfLies** [DG526/SummerProject2023#18]
In order for full credit, we will have a SMALL completed game with no less than:

- [ ]  A Main menu
- [ ] Player Customization Screen
- [ ] Mission Select Screen -or- Random Level Generation
- [ ] Twin Shooter controls for at least keyboard for movement and mouse for shooting
- [ ] Controller Support
- [ ] Local Multiplayer
- [ ] 5 different Projectiles
- [ ] Ultimate Attacks for each  Projectile type
- [ ] 6 playable level with boundaries
- [ ] 5 Power Ups - temporary bonuses
- [ ] Chests with Loot
- [ ] 3 Upgrades - Health (Hearts), Magic Power (spell specific?), Ultimate attack charges / recharge speed?
- [ ] 3 different enemy types (ankle biter, flyer, grunt)
- [ ] 5 level boss dragon with 3 different attacks, claw/claw, Bite, and a unique breath attack each
- [ ] 1 Final Boss multi-headed dragon
- [ ] Game Over Screen (with stats for the run)
- [ ] High score / player history screen
